# -*- coding: utf-8 -*-
"""nobelprizewinners.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5FQNKH19ijzmNxKYyROnd9D5Uyicl-a
"""

import pandas as pd

df=pd.read_csv('nobel.csv')
df.head(10)

df1=df.dropna()
df1.info()

df.info()

df2 = df.drop('motivation', axis=1)
df2.info()

df3 = df.iloc[:, :-6] #Drop last 5 columns
print(df3.info())

df4= df3.dropna()
df4.info()

# prompt: make df to csv

df4.to_csv('nobel_cleaned.csv', index=False)

df2.to_csv('nobel_cleaned2.csv', index=False)

